id: P7170188A
initial_creation_type: input
source_metadata:
  Title: Sambandhaparīkṣā of Dharmakirti
  Editor: Shastri, Svami Dwarikadas
  Publisher: Bauddha Bharati
  Place of Publication: India
  Year: '1972'
  Sambandhaparīkṣā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:50:17.376654'
last_modified_at: '2022-03-08T16:50:17.376662'
